prj:
  name: back-normal
  version: v0.0.2
  id: -100 # 为本应用在信息化平台注册后的ID值

gin.release: true

port: 19000

pinpoint:
  url: pinpoint-collector.cdel.local
  agentPort: 29991
  statPort: 29992
  spanPort: 29993
  sampling:
    counterRate: 20

log.root: /web/logs

GateWay:
  timeOut: 3000
  baseUrl: http://10.20.14.174/op_v2
App2:
  timeOut: 1000
  baseUrl: http://localhost:19000

mysql:
  db: doorman
  conns:
    maxOpen: 40
    maxIdle: 2
    timeout: 500ms
    readTimeout: 10s

redis:
  poolSize: 1000
  poolTimeout: 100ms
  dialTimeout: 500ms
  readTimeout: 1s
  writeTimeout: 1500ms
  minIdleConns: 2
  ttl: 3s

kafka:
  topic: test-lxb
  group_id: back-normal-group
