prj:
  name: back-normal
  version: v0.0.2

port: 80

pinpoint:
  url: 10.59.1.140
  sampling:
    counterRate: 20

log.root: /web/logs

rpc:
  timeOut: 3000
  baseUrl:
    gateway: http://10.20.14.174/op_v2
    appTwo: http://localhost:19000

mysql:
  user: dev_user
  password: dev_password
  address: 192.168.172.50:6008
  db: doorman
  conns:
    maxOpen: 40
    maxIdle: 2
    timeout: 500ms
    readTimeout: 3s
