prj:
  name: back-normal
  version: v0.0.2
  id: -100

gin.release: true

port: 80

pinpoint:
  url: 10.59.1.140
  sampling:
    counterRate: 20

log.root: /web/logs

rpc:
  timeOut: 3000
  baseUrl:
    gateway: http://10.20.14.174/op_v2
    appTwo: http://localhost:19000

mysql:
  db: doorman
  conns:
    maxOpen: 40
    maxIdle: 2
    timeout: 500ms
    readTimeout: 10s

redis:
  poolSize: 1000
  poolTimeout: 100ms
  dialTimeout: 500ms
  readTimeout: 1s
  writeTimeout: 1500ms
  minIdleConns: 2
  ttl: 3s
