prj:
  name: back-normal
  version: v0.0.2

port: 80

log.root: /web/logs

rest:
  timeOut: 3000

mysql:
  user: dev_user
  password: dev_password
  address: 192.168.172.50:6008
  db: doorman
  conns:
    maxOpen: 40
    maxIdle: 2
    timeout: 500ms
    readTimeout: 3s
